### ISSUE TITLE
Subdomain populating as null 

### ISSUE THREAD

**Issue by stevedsimkins** [PinataCloud/submarine-me#12]
We have one user who did not have a dedicated gateway when he started using submarine.me, so any links he shared used the domain `https://null.mypinata.cloud/ipfs/` Even after creating a dedicated domain the new content created with new share links are populating the same `null` subdomain

**Comment by polluterofminds** [comment]
When this happens, the user will need to log out of submarine.me and log back in. This kicks off a syncing of the Pinata account and will apply the dedicated gateway info.

**Comment by stevedsimkins** [comment]
That worked! Closing issue
