### ISSUE TITLE
Error: Null ipfs gatewayUrl when using dedicated gateway.

### ISSUE THREAD

**Issue by Sheing** [PinataCloud/submarine-me#41]
Experiencing null ipfs gatewayUrl when using the sharing link outside of current browser or session.

**Comment by Sheing** [comment]
Seems like `sm-gateway` value is being used and stored in localStorage. And that value controls how the gatewayUrl value is defined.

**Comment by polluterofminds** [comment]
@Vallo can you take a look at this when you have a moment? @Sheing if you sign out of submarine.me and sign back in, does it fix the problem?

**Comment by Sheing** [comment]
@polluterofminds I signed out and signed back in, it works okay if i am on the same browser tab, however if i open on incognito or any separate browser, it display null again.
![image](https://user-images.githubusercontent.com/21344616/191868198-56fc7715-1233-40ba-944e-5c123b624454.png)

**Comment by Sheing** [comment]
Steps to reproduce bug:
1. Go to app.submarine.me.
2. Create or Use an existing submarine link. Copy the share link.
3. Open it up on incognito or a separate browser...safari/firefox/brave...etc.
4. Custom Logo and Custom background will be null, since `gatewayUrl` is not defined and null.

**Comment by Sheing** [comment]
If anything, that hotfix made it worst, now gatewayUrl is null entirely even on the same tab/browser session.

**Comment by Sheing** [comment]
Resolved! Great workaround, love the current fix that grabs the value from supabase. Appreciate it @polluterofminds

**Comment by Vallo** [comment]
Thanks @Sheing  for the quick feedback! closing this.
