### ISSUE TITLE
Multi-wallet support

### ISSUE THREAD

**Issue by polluterofminds** [PinataCloud/submarine-me#8]
Currently, only metamask (or similar injected wallets) is supported.

**Comment by Yuxanju** [comment]
You will need to synchronize your wallet and then you debug it with bech13

**Comment by stevedsimkins** [comment]
Could we add WalletConnect at some point? 👀

**Comment by polluterofminds** [comment]
This is done as part of this commit: https://github.com/PinataCloud/submarine-me/commit/ecf68ab5f4ed370075a33ea5f8155af1c9874e52
